#!/bin/bash
echo "Start git pre-commit hooks";
echo "Start check for secrets and passwords";
for y in $(find . -print)
    do
        if ! git diff --cached --quiet "${y}" 
        then
            git secrets -f  --install
            git secrets --register-aws
        fi
done
echo "Endcheck for secrets and passwords";

echo "End git pre-commit hooks";
