#!/bin/bash

echo "Start terraform docs";
for i in `ls -d modules/*/`;do
    if ! git diff --cached --quiet "${i}"
    then
        echo "Generating doc file: ${i}";
        terraform-docs markdown table --output-file README.md --output-mode inject "${i}";
    fi
done
echo "End terraform docs";
