on: [pull_request]
jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v10
        id: verify-changed-files
        with:
          files: |
            modules/**/*.tf

      - name: Infracost breakdown
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          for i in modules/*/ ;do
            infracost breakdown --path=${i} \
                                --format=json \
                                --out-file=/tmp/infracost-base.json
          done

      - name: Post Infracost comment
        run: |
            infracost comment github  --path=/tmp/infracost-base.json \
                                      --repo=$GITHUB_REPOSITORY \
                                      --github-token=${{github.token}} \
                                      --pull-request=${{github.event.pull_request.number}} \
                                      --behavior=update
